spring:
  jpa:
    properties:
      hibernate:
        format_sql : true
        use_sql_comments : true
        default_batch_fetch_size : 100
        dialect:
          org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  messages:
    basename: validation, securityMessage

  mvc:
    hidden-method:
      filter:
        enabled: true

logging:
  level:
    sql: debug
    web: debug
